### ISSUE TITLE
Sidekiq worker threads hanging

### ISSUE THREAD

**Issue by tak1n** [httprb/http#363]
We currently are facing a lot of hanging sidekiq workers, which pile up and finally block all sidekiq queues.

When trying to debug it I sent the TTIN signal to our sidekiq process (which triggers thread backtrace output) and got following backtraces:

https://gist.github.com/tak1n/7a074e23276a2274602e2f28f694d0e8

I then checked the TID's which hang in sidekiq busy view and all of them are related to twitter gem which uses this gem. The exact last backtrace differ from thread to thread but its always one of these two:

Case 1:

```
W, [2016-07-21T17:37:00.441454 #7]  WARN -- : Thread TID-or0j1obpo 
W, [2016-07-21T17:37:00.441797 #7]  WARN -- : /usr/local/lib/ruby/2.3.0/openssl/buffering.rb:125:in `sysread'
/usr/local/lib/ruby/2.3.0/openssl/buffering.rb:125:in `readpartial'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/timeout/null.rb:42:in `readpartial'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/connection.rb:210:in `read_more'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/connection.rb:84:in `readpartial'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/response/body.rb:48:in `to_s'
/usr/local/lib/ruby/2.3.0/forwardable.rb:189:in `empty?'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/rest/request.rb:37:in `perform'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/search_results.rb:26:in `initialize'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/rest/search.rb:33:in `new'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/rest/search.rb:33:in `search'
/home/onlim/tell_it/app/models/twitter_hashtag_content_source.rb:9:in `lookup'
/home/onlim/tell_it/app/workers/lookup_content_source_worker.rb:10:in `perform'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-middleware-0.3.0/lib/sidekiq-middleware/server/unique_jobs.rb:11:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

Case 2:

```
W, [2016-07-21T17:37:00.443264 #7]  WARN -- : Thread TID-or0vb3pzo 
W, [2016-07-21T17:37:00.444152 #7]  WARN -- : /home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/timeout/null.rb:24:in `connect'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/timeout/null.rb:24:in `connect_ssl'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/timeout/null.rb:33:in `start_tls'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/connection.rb:157:in `start_tls'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/connection.rb:38:in `initialize'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/client.rb:63:in `new'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/client.rb:63:in `perform'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/client.rb:44:in `request'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/http-1.0.4/lib/http/chainable.rb:19:in `get'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/rest/request.rb:36:in `public_send'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/rest/request.rb:36:in `perform'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/rest/utils.rb:50:in `perform_request'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/rest/utils.rb:95:in `perform_request_with_objects'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/rest/utils.rb:80:in `perform_get_with_objects'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/twitter-fa9164987839/lib/twitter/rest/timelines.rb:26:in `mentions_timeline'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/adapter-48961739666c/lib/onlim/adapter/feedback/twitter_comments.rb:38:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/bundler/gems/adapter-48961739666c/lib/onlim/adapter.rb:29:in `call'
/home/onlim/tell_it/app/workers/twitter_comments_worker.rb:40:in `perform'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:151:in `execute_job'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in process'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:362:in `perform_action_with_newrelic_trace'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-middleware-0.3.0/lib/sidekiq-middleware/server/unique_jobs.rb:18:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/logging.rb:31:in `with_context'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:128:in `block in process'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:167:in `stats'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:127:in `process'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:79:in `process_one'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/processor.rb:67:in `run'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:16:in `watchdog'
/home/onlim/tell_it/vendor/bundle/ruby/2.3.1/gems/sidekiq-4.1.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

As we are using http 1.0.4 for now I'm trying to upgrade to the newest version to see if it is fixed there.

**Comment by tarcieri** [comment]
Have you tried enabling timeouts?

**Comment by tak1n** [comment]
Nope not yet, will try that thx.

If this works I will try to form a pr for https://github.com/sferik/twitter which uses null timeout.

**Comment by tak1n** [comment]
Closing as I think twitter gem should specify timeout values through the timeout api provided by http gem.

**Comment by tak1n** [comment]
I'm currently trying to form a PR for twitter gem to let the user configure a timeout which will then be used for http's timeout api and questioning my self some things.

Even if there is no timeout specified on the ruby side (in http gem in this case) shouldn't there be a default OS Kernel / low level socket timeout? I always thought there are such default timeout values but then it does not make sense at all why those sidekiq threads are hanging for eg.: 6 days.

Maybe I don't grasp the whole things behind TCP / Socket programming and that's why I'm so confused.

Would be very helpful if anyone can suggest some resources I could read to better understand this :)

**Comment by tak1n** [comment]
I tried a get request with null timeout and it timed out after a certain time because it could not connect to the given address (http://stackoverflow.com/a/904609):

```
benny@benny-Lenovo-Y50-70:~/dev/onlim/app$ time ruby -e "require 'http';HTTP.get('http://10.255.255.255')"
/home/benny/dev/onlim/app/.gem/ruby/2.3.1/gems/http-2.0.3/lib/http/timeout/null.rb:20:in `initialize': failed to connect: Connection timed out - connect(2) for "10.255.255.255" port 80 (HTTP::ConnectionError)
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/gems/http-2.0.3/lib/http/timeout/null.rb:20:in `open'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/gems/http-2.0.3/lib/http/timeout/null.rb:20:in `connect'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/gems/http-2.0.3/lib/http/connection.rb:41:in `initialize'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/gems/http-2.0.3/lib/http/client.rb:60:in `new'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/gems/http-2.0.3/lib/http/client.rb:60:in `perform'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/gems/http-2.0.3/lib/http/client.rb:41:in `request'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/gems/http-2.0.3/lib/http/chainable.rb:75:in `request'
        from /home/benny/dev/onlim/app/.gem/ruby/2.3.1/gems/http-2.0.3/lib/http/chainable.rb:19:in `get'
        from -e:1:in `<main>'

real    2m7.362s
user    0m0.116s
sys     0m0.012s
```

I know some socket operations are in general blocking (eg read) and when there is no data it just waits until data is available. In the documentation the same for readpartial is said: http://ruby-doc.org/core-2.3.1/IO.html#method-i-readpartial. Therefore the connection is established it tries to read data but as the connection got broken it does not get anything and therefore just waits until it receives something? (which is never?)

I mean this basically explains why the threads are hanging for readpartial, but for the stack trace above where it got stuck on a connect I still don't know whats happening.

Correct me if I got anything wrong, and sorry for the noise on a closed ticket :S
