### ISSUE TITLE
SSL_connect certificate verify failed

### ISSUE THREAD

**Issue by xanview** [httprb/http#379]
I'm making a connection to an alarm which has a self signed certificate, I'm seeing this:

```ruby
?> HttpClient.basic_auth(user: "Installer", pass: "7890").get('https://192.168.0.100:4433/system/partitions/')
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
	from /var/lib/gems/2.3.0/gems/http-2.1.0/lib/http/timeout/global.rb:37:in `connect_nonblock'
	from /var/lib/gems/2.3.0/gems/http-2.1.0/lib/http/timeout/global.rb:37:in `connect_ssl'
	from /var/lib/gems/2.3.0/gems/http-2.1.0/lib/http/timeout/null.rb:35:in `start_tls'
	from /var/lib/gems/2.3.0/gems/http-2.1.0/lib/http/connection.rb:158:in `start_tls'
	from /var/lib/gems/2.3.0/gems/http-2.1.0/lib/http/connection.rb:44:in `initialize'
	from /var/lib/gems/2.3.0/gems/http-2.1.0/lib/http/client.rb:60:in `new'
	from /var/lib/gems/2.3.0/gems/http-2.1.0/lib/http/client.rb:60:in `perform'
	from /var/lib/gems/2.3.0/gems/http-2.1.0/lib/http/client.rb:41:in `request'
	from /var/lib/gems/2.3.0/gems/http-2.1.0/lib/http/chainable.rb:19:in `get'
	from (irb):8
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /var/lib/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Is there anyway to allow insecure ssl certificates and/or self signed certificated?

**Comment by xanview** [comment]
I found an issue and a workaround here: #308 - but it would be great if a cleaner solution was available or some way to set the context in a reusable client object, e.g.:

```ruby
HttpClient = HTTP.timeout(:global, write: 120, connect: 30, read: 120).insecure
HttpClient.get('https://192.168.0.100/example')
```

**Comment by tarcieri** [comment]
Dup of #308
