### ISSUE TITLE
Incompatible character encodings with non-english characters

### ISSUE THREAD

**Issue by icyleaf** [httprb/http#427]
ENV

```
os: macOS 10.12.6
ruby: 2.4.1 with rvm
http: 2.2.2
```

It throws exception if it passed non-english characters with file to post form.
```ruby
form_data = {
  name: '你好',
  file: HTTP::FormData::File.new('README.md')
}

form_data.map {|k,v| puts "#{k} encode: #{v.to_s.encoding}" }

r = HTTP.post 'http://bing.com', form: form_data
puts r
```

resule: 

```
name encode: UTF-8
file encode: ASCII-8BIT

Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
/Users/wiiseer/.rvm/gems/ruby-2.4.1@qyer-mobile-app/gems/http-form_data-1.0.3/lib/http/form_data/multipart.rb:22:in `join'
/Users/wiiseer/.rvm/gems/ruby-2.4.1@qyer-mobile-app/gems/http-form_data-1.0.3/lib/http/form_data/multipart.rb:22:in `to_s'
/Users/wiiseer/.rvm/gems/ruby-2.4.1@qyer-mobile-app/gems/http-2.2.2/lib/http/client.rb:164:in `make_request_body'
/Users/wiiseer/.rvm/gems/ruby-2.4.1@qyer-mobile-app/gems/http-2.2.2/lib/http/client.rb:30:in `request'
/Users/wiiseer/.rvm/gems/ruby-2.4.1@qyer-mobile-app/gems/http-2.2.2/lib/http/chainable.rb:75:in `request'
/Users/wiiseer/.rvm/gems/ruby-2.4.1@qyer-mobile-app/gems/http-2.2.2/lib/http/chainable.rb:26:in `post'
```

Why file encode was `ASCII-8Bit` ?

**Comment by tarcieri** [comment]
@icyleaf thanks, this does indeed look like an encoding bug

**Comment by janko-m** [comment]
This now works correctly with latest `http` and `http-form_data` gems.

```rb
require "http"

form_data = {
  name: '你好',
  file: HTTP::FormData::File.new(__FILE__)
}

form_data.map {|k,v| puts "#{k} encode: #{v.to_s.encoding}" }

p HTTP.post("http://example.com", form: form_data)
```
```
name encode: UTF-8
file encode: ASCII-8BIT
#<HTTP::Response/1.1 200 OK {"Accept-Ranges"=>"bytes", "Cache-Control"=>"max-age=604800", "Content-Type"=>"text/html; charset=UTF-8", "Date"=>"Sun, 18 Nov 2018 09:11:37 GMT",
"Etag"=>"\"1541025663\"", "Expires"=>"Sun, 25 Nov 2018 09:11:37 GMT", "Last-Modified"=>"Fri, 09 Aug 2013 23:54:35 GMT", "Server"=>"EOS (vny006/0450)", "Content-Length"=>"1270"
, "Connection"=>"close"}>
```
