### ISSUE TITLE
HTTP::Parser::Error in case of closed connection

### ISSUE THREAD

**Issue by tycooon** [httprb/http#556]
```ruby
> HTTP.post("https://api.sendgrid.com/v3/mail/send123", body: "d" * 10000)
```
```
HTTP::ConnectionError: error reading from socket: Could not parse data entirely (1 != 0)
from /Users/tycooon/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/http-4.1.1/lib/http/response/parser.rb:14:in `<<'
Caused by HTTP::Parser::Error: Could not parse data entirely (1 != 0)
from /Users/tycooon/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/http-4.1.1/lib/http/response/parser.rb:14:in `<<'
```

It looks like Sendgrid server is closing connection in case we try to POST a lot of data to some unknown endpoint. In this case we are getting HTTP::Parser::Error which is not very cool. For example, Net::HTTP is just ignoring missing body:

```ruby
> Net::HTTP.post(URI("https://api.sendgrid.com/v3/mail/send123"), "d" * 10000)
=> #<Net::HTTPNotFound 404 Not Found readbody=true>
> _.body
=> ""
```

RestClient behaves the same as Net::HTTP.

**Comment by ixti** [comment]
Although I see how that is not very cool. I don't think that swallowing errors and silently returning empty body is good idea... It's not client's responsibility to handle that kinds of errors IMO.

I mean if it's OK with body silently returning empty string in case of underlying error, then probably there's no value in that body anyway, and you can simply ignore it. Or you can catch that exception.

Also, if we would swallow connection close during body streaming, would we need to silently swallow connection errors when they happen earlier (like during http headers send)?...

**Comment by ixti** [comment]
What I mean is, let's say our server behaves like this:

``` ruby
# frozen_string_literal: true

require "socket"

server = TCPServer.new(8080)

while (socket = server.accept)
  req = socket.gets[%r{^GET /([^ ]+)}, 1]

  socket << "HTTP/1.1 404 Not Found\r\n"
  socket << "Content-Type: text/plain\r\n"
  socket << "Content-Length: 161\r\n"

  case req
  when "a"
    socket << "X-Half: Heade"
  when "b"
    socket << "\r\n"
    socket << "half-bo"
  when "c"
    socket << "\r\n"
  end

  socket.close
end
```

Technically I think we can make client ignore any of those errors and return empty string as a body, but is it correct? Or is it what majority of users will expect? I don't know.

Probably it's actually a task for a *Session* class that would handle redirects and cookies in future.

**Comment by tycooon** [comment]
Well, maybe we can add some new error class for such cases to make handling easier. Or maybe even some configuration. Right now users see some generic exception in case where other libs are “just working” and they are frustrated. I also didn’t mention that when using persistent connections, you are actually getting another error after initial request: the one saying you did not read the body of the previous request.

**Comment by tarcieri** [comment]
> Right now users see some generic exception in case where other libs are “just working” and they are frustrated.

You named `Net::HTTP` and RestClient, which is a `Net::HTTP` wrapper. Have you investigated how other clients which aren't based on `Net::HTTP` behave?

Either this is a bug in our parser, or it's a framing error in the response. If it's the latter, my personal inclination is that it remain an error. The problem with trying to make it "just work", as @ixti already noted, is that such behaviors could manifest as silent truncation or corruption of response bodies.

**Comment by tycooon** [comment]
HTTPClient also swallows the error. I am not sure that we should do that, but here are the actual problems that I see in the current behaviour:
1. The error raised is `HTTP::ConnectionError` which is hard to handle since it's raised in many different situations.
2. The error occurs when trying to read the response body (and it leaves that unread) so basically it breaks the persistent client.

**Comment by tarcieri** [comment]
Some sort of `EOFError` would probably be a better fit for this case.

> HTTPClient also swallows the error

@tycooon any chance you can try to reproduce this with curl and see what it does?

**Comment by tycooon** [comment]
Sure, it returns the error:
```
curl: (18) transfer closed with 19 bytes remaining to read
```

**Comment by tarcieri** [comment]
Okay, nice to get a sanity check on that. I'd argue that what Net::HTTP and HTTPClient are doing is wrong.
